/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Francisco Paxtian
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    //COMPONENTES DE LA VENTANA
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtRutinas2 = new javax.swing.JButton();
        BtRutinas = new javax.swing.JButton();
        BtUsuarios = new javax.swing.JButton();
        BtPago = new javax.swing.JButton();
        BtMiembros = new javax.swing.JButton();
        BtInventarios = new javax.swing.JButton();
        BtEmpleado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU PRINCIPAL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 300, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO EQUIPO TRANS 75x75.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 80));

        BtRutinas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REGISTRORUTINAS ICON.png"))); // NOI18N
        BtRutinas2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtRutinas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRutinas2ActionPerformed(evt);
            }
        });
        jPanel2.add(BtRutinas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 150, 150));

        BtRutinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RUTINAS ICON.png"))); // NOI18N
        BtRutinas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRutinasActionPerformed(evt);
            }
        });
        jPanel2.add(BtRutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 150, 150));

        BtUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/USUARIOS ICON.png"))); // NOI18N
        BtUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(BtUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 150));

        BtPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PAGO ICON.png"))); // NOI18N
        BtPago.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPagoActionPerformed(evt);
            }
        });
        jPanel2.add(BtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 150, 150));

        BtMiembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MIEMBROS ICON.png"))); // NOI18N
        BtMiembros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMiembrosActionPerformed(evt);
            }
        });
        jPanel2.add(BtMiembros, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 150, 150));

        BtInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/INVENTARIOS ICON.png"))); // NOI18N
        BtInventarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInventariosActionPerformed(evt);
            }
        });
        jPanel2.add(BtInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 150));

        BtEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EMPLEADOS ICON.png"))); // NOI18N
        BtEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(BtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, 150));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Socios");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 100, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuarios");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Empleados");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, 50));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rutinas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inventarios");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 170, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pagos");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, 30));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registro rutinas");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU (1)_1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//BOTON QUE CONECTA A LA VENTANA DE REGISTRO RUTINAS
    private void BtRutinas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRutinas2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroRutinas().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtRutinas2ActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE RUTINAS
    private void BtRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRutinasActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rutinas().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtRutinasActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE USUARIOS
    private void BtUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUsuariosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtUsuariosActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE PAGOS
    private void BtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPagoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagos().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtPagoActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE MIEMBROS
    private void BtMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMiembrosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socios().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtMiembrosActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE INVENTARIOS
    private void BtInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInventariosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventarios().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtInventariosActionPerformed
//BOTON QUE CONECTA A LA VENTANA DE EMPLEADOS
    private void BtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEmpleadoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEmpleado;
    private javax.swing.JButton BtInventarios;
    private javax.swing.JButton BtMiembros;
    private javax.swing.JButton BtPago;
    private javax.swing.JButton BtRutinas;
    private javax.swing.JButton BtRutinas2;
    private javax.swing.JButton BtUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
