/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import Conexion.ConexionGYM;
import MetodosDAO.SociosDAO;
import MetodosVO.SociosVO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Paxtian
 */
public class Socios extends javax.swing.JFrame {
    private final ConexionGYM CON;
    Statement ps;
    private ResultSet rs;
    /**
     * Creates new form Socios
     */
    public Socios() {
        initComponents();
        setLocationRelativeTo(null);
        CON = ConexionGYM.getInstacia();
        transparenciaButton();
        mostrarA();
    }

    String [] botones = {"Gris oscuro","Gris","Cafe","Verde","Celeste","Amarillo"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtAyuda = new javax.swing.JButton();
        BtColor = new javax.swing.JButton();
        BtVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaA = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        BtGuardar = new javax.swing.JButton();
        BtCambiar1 = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Con = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BtConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        Barra.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO DEL GYM BLANCO 50x50.png"))); // NOI18N

        BtAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AYUDA 40x40.png"))); // NOI18N
        BtAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAyudaActionPerformed(evt);
            }
        });

        BtColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COLOR 40x40.png"))); // NOI18N
        BtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtColorActionPerformed(evt);
            }
        });

        BtVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VOLVER 40x40.png"))); // NOI18N
        BtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVolverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Socios");

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(346, 346, 346)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(BtAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtVolver)
                    .addComponent(BtAyuda)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel4.setText("ID SOCIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        TablaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SOCIO", "NOMBRE", "APELLIDO", "GENERO", "EDAD", "TELEFONO", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 940, 250));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setText("NOMBRE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel6.setText("APELLIDO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setText("TELEFONO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setText("EMAIL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel9.setText("GENERO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 690, 30));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel10.setText("EDAD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, 30));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 260, 30));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 260, 30));
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 260, 30));

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        getContentPane().add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 260, 30));
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 260, 30));
        getContentPane().add(Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 260, 30));

        BtGuardar.setBackground(new java.awt.Color(255, 102, 0));
        BtGuardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        BtGuardar.setText("GUARDAR SOCIO");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 30));

        BtCambiar1.setBackground(new java.awt.Color(255, 102, 0));
        BtCambiar1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        BtCambiar1.setText("CAMBIAR DATOS");
        BtCambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCambiar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtCambiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 190, 30));

        BtEliminar.setBackground(new java.awt.Color(255, 102, 0));
        BtEliminar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        BtEliminar.setText("ELIMINAR SOCIO");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 190, 30));

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SOCIO", "NOMBRE", "APELLIDO", "GENERO", "EDAD", "TELEFONO", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(T1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 940, 60));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONSULTA INDIVIDUAL");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));
        getContentPane().add(Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 110, 30));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        jLabel12.setText("INGRESE EL NOMBRE DEL SOCIO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 300, 30));

        BtConsultar.setBackground(new java.awt.Color(255, 102, 0));
        BtConsultar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        BtConsultar.setText("CONSULTAR");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(BtConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SOCIOS VENTANA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    SociosVO AV = new SociosVO();
    SociosDAO AD = new SociosDAO();
    
    
    public void transparenciaButton(){
        BtAyuda.setOpaque(false);
        BtAyuda.setContentAreaFilled(false);
        BtAyuda.setBorderPainted(false);
        BtVolver.setOpaque(false);
        BtVolver.setContentAreaFilled(false);
        BtVolver.setBorderPainted(false);
        BtColor.setOpaque(false);
        BtColor.setContentAreaFilled(false);
        BtColor.setBorderPainted(false);
    }
  
    DefaultTableModel modelA;
        void mostrarA(){
        String sql= "select * from socios";
        try {
            Connection ConexionGYM = CON.conectar();
            ps=CON.conectar().createStatement();
            rs = ps.executeQuery(sql);
            Object [] socios = new Object[7];
            modelA = (DefaultTableModel) TablaA.getModel();
            while(rs.next()){
                socios [0] = rs.getString("id_socio");
                socios [1] = rs.getString("nombre");
                socios [2] = rs.getString("apellido");
                socios [3] = rs.getString("genero");
                socios [4] = rs.getString("edad");
                socios [5] = rs.getString("telefono");
                socios [6] = rs.getString("email");
                modelA.addRow(socios);
            }
            TablaA.setModel(modelA);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error...");
        }        
    }
   void limpiarA(){
        for (int i =0 ; i<=TablaA.getRowCount(); i++){
            modelA.removeRow(i);
            i = i-1;
        }
    }
    void insertar(){
        
        String id_socio=Id.getText();
        String nombre=Nombre.getText();
        String apellido=Apellido.getText();
        String genero=Genero.getText();
        String edad=Edad.getText();
        String telefono=Telefono.getText();
        String email=Email.getText();
    
        try{
            if(id_socio.equals("") || nombre.equals("") || apellido.equals("") || genero.equals("") || edad.equals("") || telefono.equals("") || email.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos del usuario.");
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps = ConexionGYM.createStatement();
                String sql = "insert into socios values('"+id_socio+"','"+nombre+"','"+apellido+"','"+genero+"','"+edad+"','"+telefono+"','"+email+"')";
                ps.execute(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Socio registrado.");
                limpiarA();             
            }
        }catch(Exception e){
            //System.out.println("Error al insertar");
        }
    }
     void modificar(){
        
        String id_socio=Id.getText();
        String nombre=Nombre.getText();
        String apellido=Apellido.getText();
        String genero=Genero.getText();
        String edad=Edad.getText();
        String telefono=Telefono.getText();
        String email=Email.getText();
        
        try{
            if(id_socio.equals("") || nombre.equals("") || apellido.equals("") || genero.equals("") || edad.equals("") || telefono.equals("") || email.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos.");
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps=ConexionGYM.createStatement();
                String sql = "update socios set nombre='"+nombre+"', apellido='"+apellido+"', genero='"+genero+"', edad='"+edad+"', telefono='"+telefono+"', email='"+email+"' where id_socio='" +id_socio+ "'; ";
                ps.executeUpdate(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Socio actualizado.");
                limpiarA();
            }
            
        }catch(Exception e){
            //System.out.println("Usuario no registrado");
        }
        
    }
    
        void eliminar(){
        String id_socio=Id.getText();
        //int fila = TablaA.getSelectedRow();
        try{
            if(id_socio.equals("")){
               JOptionPane.showMessageDialog(null, "Socio no seleccionado");
               limpiarA();
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps=ConexionGYM.createStatement();
                String sql="delete from socios where id_socio='"+id_socio+"'; ";
                ps.executeUpdate(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Socio dado de baja");
                limpiarA();
            }
             
        }catch(Exception e){
         
        }
    
    }
    public void ConsultaSoc(){
        String NOMBRE=Con.getText();
        String sql= "SELECT * FROM socios WHERE nombre ='"+NOMBRE+"';";
        try {
            Connection ConexionGYM = CON.conectar();
            ps=CON.conectar().createStatement();
            rs = ps.executeQuery(sql);
            Object [] cons = new Object[7];
            modelA = (DefaultTableModel) T1.getModel();
            while(rs.next()){
                cons [0] = rs.getString("id_socio");
                cons [1] = rs.getString("nombre");
                cons [2] = rs.getString("apellido");
                cons [3] = rs.getString("genero");
                cons [4] = rs.getString("edad");
                cons [5] = rs.getString("telefono");
                cons [6] = rs.getString("email");
                modelA.addRow(cons);
            }
            T1.setModel(modelA);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error...");
        }
    }
    public void limpiar(){
        modelA.getDataVector().removeAllElements();
        T1.updateUI();
    } 
    
    private void BtAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "★Seccion de socios★ \n ☛ Primero llena las casillas con los datos que se pide "
        + "\n ☛ Despues seleccione la accion a realizar \n ☛ Los datos registrados apareceran en la parte inferior \n ⇩ Para dar baja solo ingrese el id del socio");
        JOptionPane.showMessageDialog(rootPane, "Para mas ayuda y asistencia tecnica contactenos \n ✉ Correo: fpaxtian@hotmail.com \n "
        + "☎ Telefono: 9621848035");
        JOptionPane.showMessageDialog(rootPane, "Programa desarrollado por: \n♛ Francisco Javier Paxtian Gordillo ");
    }//GEN-LAST:event_BtAyudaActionPerformed

    private void BtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtColorActionPerformed
        int x = JOptionPane.showOptionDialog(this,"Elige un color","Color de la barra superior",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones,botones[0]);
        if(x==0){
            Barra.setBackground(Color.darkGray);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==1){
            Barra.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==2){
            Color colorCafe=new Color(144, 68, 7);
            Barra.setBackground(colorCafe);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==3){
            Color colorVerde=new Color(0, 204, 0);
            Barra.setBackground(colorVerde);
            JOptionPane.showMessageDialog(this,"Color aplicado!");   
        }else if(x==4){
            Color colorCeleste=new Color(0, 179, 207);
            Barra.setBackground(colorCeleste);
            JOptionPane.showMessageDialog(this,"Color aplicado!");            
        }else if(x==5){
            Color colorAmarillo=new Color(255, 203, 34);
            Barra.setBackground(colorAmarillo);
            JOptionPane.showMessageDialog(this,"Color aplicado!");              
        }
    }//GEN-LAST:event_BtColorActionPerformed

    private void BtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVolverActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtVolverActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed
        // TODO add your handling code here:
        insertar();
        mostrarA();
    }//GEN-LAST:event_BtGuardarActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void BtCambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCambiar1ActionPerformed
        // TODO add your handling code here:
        modificar();
        mostrarA();
    }//GEN-LAST:event_BtCambiar1ActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
        mostrarA();
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        limpiar();
        ConsultaSoc();
    }//GEN-LAST:event_BtConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JPanel Barra;
    private javax.swing.JButton BtAyuda;
    private javax.swing.JButton BtCambiar1;
    private javax.swing.JButton BtColor;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JButton BtVolver;
    private javax.swing.JTextField Con;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Genero;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTable T1;
    private javax.swing.JTable TablaA;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
