/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import Conexion.ConexionGYM;
import MetodosDAO.UsuariosDAO;
import MetodosVO.UsuariosVO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Paxtian
 */
public class Usuarios extends javax.swing.JFrame {
    private final ConexionGYM CON;
    Statement ps;
    private ResultSet rs;
    /**
     * Creates new form Usuarios
     */
    //COMPONENTES DE LA VENTANA
    public Usuarios() {
        initComponents();
        setLocationRelativeTo(null);
        CON = ConexionGYM.getInstacia();
        transparenciaButton();
        mostrarA();
    }
    //LINEA ENCARGADA DE LOS BOTONES DE UNA VENTANA EMERGENTE
    String [] botones = {"Gris oscuro","Gris","Cafe","Azul","Morado","Verde"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    UsuariosDAO AD = new UsuariosDAO();
    UsuariosVO AV = new UsuariosVO();
    //FUNCION ENCARGADA DE TRANSPARENTAR LOS BOTONES SUPERIORES DE LA VENTANA
    public void transparenciaButton(){
        BtAyuda.setOpaque(false);
        BtAyuda.setContentAreaFilled(false);
        BtAyuda.setBorderPainted(false);
        BtVolver.setOpaque(false);
        BtVolver.setContentAreaFilled(false);
        BtVolver.setBorderPainted(false);
        BtColor.setOpaque(false);
        BtColor.setContentAreaFilled(false);
        BtColor.setBorderPainted(false);
    }
    //FUNCION ENCARGADA DE MOSTRAR LOS DATOS REGISTRADOS DE LA BD EN LA TABLA
    DefaultTableModel modelA;
        void mostrarA(){
        String sql= "select * from admin";
        try {
            Connection ConexionGYM = CON.conectar();
            ps=CON.conectar().createStatement();
            rs = ps.executeQuery(sql);
            Object [] usuarios = new Object[5];
            modelA = (DefaultTableModel) TablaA.getModel();
            while(rs.next()){
                usuarios [0] = rs.getString("usuario");
                usuarios [1] = rs.getString("contrasena");
                modelA.addRow(usuarios);
            }
            TablaA.setModel(modelA);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error...");
        }        
    }
   void limpiarA(){
        for (int i =0 ; i<=TablaA.getRowCount(); i++){
            modelA.removeRow(i);
            i = i-1;
        }
    }
   //FUNCION ENCARGADA DE LA INSERCION DE DATOS INGRESADOS
    void insertar(){
        
        String usuario=Usuario.getText();
        String clave=Contra.getText();
    
        try{
            if(usuario.equals("") || clave.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos del usuario.");
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps = ConexionGYM.createStatement();
                String sql = "insert into admin values('"+usuario+"','"+clave+"')";
                ps.execute(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Usuario registrado.");
                limpiarA();             
            }
        }catch(Exception e){
            //System.out.println("Error al insertar");
        }
    }
    //FUNCION ENCARGADA DE MODIFICAR LOS DATOS INGRESADOS
    void modificar(){
        
        String usuario=Usuario.getText();
        String clave=Contra.getText();
        
        try{
            if(usuario.equals("") || clave.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan datos.");
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps=ConexionGYM.createStatement();
                String sql = "update admin set Contrasena='" + clave + "' where Usuario='" +usuario+ "'; ";
                ps.executeUpdate(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Contraseña actualizado.");
                limpiarA();
            }
            
        }catch(Exception e){
            //System.out.println("Usuario no registrado");
        }
        
    }
    //FUNCION ENCARGADA DE ELIMINAR LOS USUARIOS
        void eliminar(){
        String usuario=Usuario.getText();
        //int fila = TablaA.getSelectedRow();
        try{
            if(usuario.equals("")){
               JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
               limpiarA();
            }else{
                Connection ConexionGYM = CON.conectar();
                java.sql.Statement ps=ConexionGYM.createStatement();
                String sql="delete from admin where Usuario='"+usuario+"'; ";
                ps.executeUpdate(sql);
                ConexionGYM.close();
                JOptionPane.showMessageDialog(null, "Usuario eliminado");
                limpiarA();
            }
             
        }catch(Exception e){
         
        }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtAyuda = new javax.swing.JButton();
        BtColor = new javax.swing.JButton();
        BtVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Contra = new javax.swing.JTextField();
        BtGuardar = new javax.swing.JButton();
        Usuario = new javax.swing.JTextField();
        BtCambiar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO DEL GYM BLANCO 50x50.png"))); // NOI18N

        BtAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AYUDA 40x40.png"))); // NOI18N
        BtAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAyudaActionPerformed(evt);
            }
        });

        BtColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COLOR 40x40.png"))); // NOI18N
        BtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtColorActionPerformed(evt);
            }
        });

        BtVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VOLVER 40x40.png"))); // NOI18N
        BtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVolverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuarios");

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(319, 319, 319)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(BtAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtVolver)
                    .addComponent(BtAyuda)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        jPanel1.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 270, 30));

        BtGuardar.setBackground(new java.awt.Color(255, 255, 0));
        BtGuardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        BtGuardar.setText("GUARDAR USUARIO");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(BtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 180, 30));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 270, 30));

        BtCambiar.setBackground(new java.awt.Color(255, 255, 0));
        BtCambiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        BtCambiar.setText("CAMBIAR CONTRASEÑA");
        BtCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 180, 30));

        BtEliminar.setBackground(new java.awt.Color(255, 255, 0));
        BtEliminar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        BtEliminar.setText("ELIMINAR USUARIO");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 180, 30));

        TablaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USUARIO", "CONTRASEÑA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 880, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/USUARIOS VENTANA.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//BOTON QUE REGRESA AL MENU PRINCIPAL
    private void BtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVolverActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BtVolverActionPerformed
//BOTON QUE CAMBIA EL COLOR DE LA BARRA SUPERIOR
    private void BtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtColorActionPerformed
        int x = JOptionPane.showOptionDialog(this,"Elige un color","Color de la barra superior",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,null,botones,botones[0]);
        if(x==0){
            Barra.setBackground(Color.darkGray);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==1){
            Barra.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==2){
            Color colorCafe=new Color(144, 68, 7);
            Barra.setBackground(colorCafe);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==3){
            Color colorAzul=new Color(0, 0, 153);
            Barra.setBackground(colorAzul);
            JOptionPane.showMessageDialog(this,"Color aplicado!");
        }else if(x==4){
            Color colorMorado=new Color(153, 0, 153);
            Barra.setBackground(colorMorado);
            JOptionPane.showMessageDialog(this,"Color aplicado!");            
        }else if(x==5){
            Color colorVerde=new Color(0, 204, 0);
            Barra.setBackground(colorVerde);
            JOptionPane.showMessageDialog(this,"Color aplicado!");              
        }
    }//GEN-LAST:event_BtColorActionPerformed
//BOTON DE ASISTENCIA AL USUARIO
    private void BtAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "★Seccion de usuarios★ \n ☛ Primero llena las casillas con los datos que se pide "
        + "\n ☛ Despues seleccione la accion a realizar \n ☛ Los datos registrados apareceran en la parte inferior \n ⇩ Para dar baja solo ingrese el usuario");
        JOptionPane.showMessageDialog(rootPane, "Para mas ayuda y asistencia tecnica contactenos \n ✉ Correo: fpaxtian@hotmail.com \n "
        + "☎ Telefono: 9621848035");
        JOptionPane.showMessageDialog(rootPane, "Programa desarrollado por: \n♛ Francisco Javier Paxtian Gordillo ");
    }//GEN-LAST:event_BtAyudaActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed
//BOTON QUE GUARDA LOS DATOS INGRESADOS
    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed
        // TODO add your handling code here:
        insertar();
        mostrarA();
    }//GEN-LAST:event_BtGuardarActionPerformed
//BOTON QUE MODIFICA LOS DATOS INGRESADOS
    private void BtCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCambiarActionPerformed
        // TODO add your handling code here:
        modificar();
        mostrarA();
    }//GEN-LAST:event_BtCambiarActionPerformed
//BOTON QUE ELIMINA UN USUARIO
    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
        mostrarA();
    }//GEN-LAST:event_BtEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JButton BtAyuda;
    private javax.swing.JButton BtCambiar;
    private javax.swing.JButton BtColor;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JButton BtVolver;
    private javax.swing.JTextField Contra;
    private javax.swing.JTable TablaA;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
